name: notebooks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # trigger manually from GitHub UI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: ["3.13"]
        notebook-dir: ["composite", "large_data", "lin", "multivariate", "univariate"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"


      - name: Install Package
        run: uv sync --locked --group dev

      - name: Prepare large-data notebook
        if: matrix.notebook-dir == 'large_data'
        run: |
          uv run mystnb-to-jupyter notebooks/large_data/test_large_data.md
          uv pip install "liesel @ git+https://github.com/liesel-devs/liesel.git@de73db78af7f9385d1b50db01aa90a25e882e634"

      - name: Run pytest
        run: uv run --no-sync pytest notebooks/${{ matrix.notebook-dir }} --nbval-lax --nbval-current-env
